import "@/styles/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import Analytics from '@/components/analytics';
import { GoogleAnalytics } from '@next/third-parties/google'
import { Toaster } from "ai-uis";
import { Inter } from "next/font/google";
import { cn } from "ai-utilities";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ali Imam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="76x76" href="/favicon.svg" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.svg" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon.svg" />
        <meta name="google-adsense-account" content="ca-pub-8509771369416706" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="theme-color" content="#000000" />
        <link rel="alternate" type="application/rss+xml" href="/feed.xml" />
      </head>
      <body className={cn("bg-white dark:bg-black", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Toaster />
          <Footer />
          <Analytics />
          <GoogleAnalytics gaId="G-7DJXCEPQ1E" />
        </ThemeProvider>
      </body>
    </html>
  );
}
